import { useShopProducts } from "@/hooks/shop/useShopProducts";
import { useApiErrorToast } from "@/services/api/useApiErrorToast";
import { useShopStore } from "@/store/shop/useShopStore";
import { shopId, type AutogenShopLifecycle, type ShopId } from "@/types/shop";
import { useEffect, useMemo, useRef, useState } from "react";

/**
 * Hook to watch autogenerated shops and detect backend errors.
 * Only considers shops that already exist in the store.
 */
interface BackendAvailabilityOptions {
  delayMs?: number;
  enabled?: boolean;
}

export function useBackendAvailability(
  shopId: ShopId | null,
  options?: BackendAvailabilityOptions
) {
  const { delayMs = 800, enabled = true } = options ?? {};
  const [armed, setArmed] = useState(false);

  // Arm the probe AFTER delay
  useEffect(() => {
    if (!enabled || !shopId) return;

    const t = setTimeout(() => setArmed(true), delayMs);
    return () => clearTimeout(t);
  }, [enabled, shopId, delayMs]);

  // Probe the backend for shop products
  const { loading, error, hydrated } = useShopProducts(shopId, {
    enabled: armed,
    forceBackend: true,
  });

  return {
    checking: armed && loading,
    available: armed && hydrated && !error,
    unavailable: armed && !!error,
    error,
  };
}

// Hook to watch multiple shops and detect backend errors.

export type AutogenLibraryId = "FLORIST" | "CAFETERIA";

// Hook for AUTOGEN libraries only
export function useAutogenAvailability(
  libraries: AutogenLibraryId[],
  enabled: boolean
) {
  const [armed, setArmed] = useState(false);
  const shopStore = useShopStore();
  const fetchedRef = useRef<Set<string>>(new Set()); // Track already fetched AUTOGEN shops
  const errorRef = useRef<unknown>(null);

  // Delay arming the hook
  useEffect(() => {
    if (!enabled || libraries.length === 0) return;
    const t = setTimeout(() => setArmed(true), 500);
    return () => clearTimeout(t);
  }, [enabled, libraries]);

  // Prepare AUTOGEN slices
  const slices = useMemo(() => {
  return libraries
    .map((lib) => {
      const id = shopId(lib) as ShopId; // <-- cast to ShopId
      const slice = shopStore.shops[id];

      // Only AUTOGEN shops
      if (!slice || slice.kind !== "AUTOGEN") return null;

      return { lib, id, slice, lifecycle: slice.lifecycle };
    })
    .filter(Boolean) as {
      lib: AutogenLibraryId;
      id: ShopId;
      slice: typeof shopStore.shops[ShopId];
      lifecycle: typeof shopStore.shops[ShopId]["lifecycle"];
    }[];
}, [libraries, shopStore.shops]);


  // Trigger backend ABC fetch safely
  useEffect(() => {
    if (!armed) return;

    slices.forEach(({ id, slice, lifecycle }) => {
      const hydrated = slice?.hydrated ?? false;
      const shouldFetch =
        (!hydrated || lifecycle === "CREATED" || lifecycle === "IMPORTING") &&
        !fetchedRef.current.has(id);

      if (!shouldFetch) return;

      fetchedRef.current.add(id);

      shopStore
        .runABC({ executionMode: "BACKEND", simulationType: "classic", shopId: id })
        .catch((err) => {
          // Store error in ref for toast
          errorRef.current = slice?.abc?.error ?? err;
        });
    });
  }, [armed, slices, shopStore]);

  // Show toast when error occurs
  useApiErrorToast(errorRef.current, "Autogen Shop");

  // Build availability info
  const perLibrary = slices.map(({ lib, slice, lifecycle }) => {
    const abcLoading = slice?.abc?.loading ?? false;
    const abcError = slice?.abc?.error;

    const unavailable = armed && (lifecycle === "FAILED" || !!abcError);
    const available = armed && lifecycle === "READY";

    return { lib, lifecycle, unavailable, available, loading: abcLoading };
  });

  return {
    unavailable: perLibrary.some((r) => r.unavailable),
    checking: armed && perLibrary.some((r) => r.loading),
    perLibrary,
  };
}



