import { useShopProducts } from "@/hooks/shop/useShopProducts";
import { useApiErrorToast } from "@/services/api/useApiErrorToast";
import { useShopStore } from "@/store/shop/useShopStore";
import { shopId, type AutogenShopLifecycle, type ShopId } from "@/types/shop";
import { useEffect, useMemo, useRef, useState } from "react";

/**
 * Hook to watch autogenerated shops and detect backend errors.
 * Only considers shops that already exist in the store.
 */
interface BackendAvailabilityOptions {
  delayMs?: number;
  enabled?: boolean;
}

export function useBackendAvailability(
  shopId: ShopId | null,
  options?: BackendAvailabilityOptions
) {
  const { delayMs = 800, enabled = true } = options ?? {};
  const [armed, setArmed] = useState(false);

  // Arm the probe AFTER delay
  useEffect(() => {
    if (!enabled || !shopId) return;

    const t = setTimeout(() => setArmed(true), delayMs);
    return () => clearTimeout(t);
  }, [enabled, shopId, delayMs]);

  // Probe the backend for shop products
  const { loading, error, hydrated } = useShopProducts(shopId, {
    enabled: armed,
    forceBackend: true,
  });

  return {
    checking: armed && loading,
    available: armed && hydrated && !error,
    unavailable: armed && !!error,
    error,
  };
}

// Hook to watch multiple shops and detect backend errors.

export type AutogenLibraryId = "FLORIST" | "CAFETERIA";

/**
 * Ensures AUTOGEN shops exist in the store.
 */
export function useEnsureAutogenShops(libraries: AutogenLibraryId[]) {
  const setShop = useShopStore((s) => s.setShop);

  useEffect(() => {
    libraries.forEach((lib) => {
      const id = shopId(lib) as ShopId;
      const slice = useShopStore.getState().shops[id];
      if (!slice) {
        setShop({
          id,
          name: lib,
          kind: "AUTOGEN",
          lifecycle: "CREATED",
        });
      }
    });
  }, [libraries, setShop]);
}

/**
 * Watches AUTOGEN shops and triggers backend ABC fetch.
 */

export type AutogenAvailabilityEntry = {
  lib: AutogenLibraryId;
  lifecycle: "CREATED" | "IMPORTING" | "READY" | "FAILED";
  unavailable: boolean;
  available: boolean;
  loading: boolean;
};

export type AutogenAvailabilityResult = {
  unavailable: boolean;
  checking: boolean;
  perLibrary: AutogenAvailabilityEntry[];
};

export function useAutogenAvailability(
  libraries: AutogenLibraryId[],
  enabled: boolean
): AutogenAvailabilityResult {

  const shopStore = useShopStore();
  const [armed, setArmed] = useState(false);
  const fetchedRef = useRef<Set<ShopId>>(new Set());
  const errorRef = useRef<unknown>(null);

  // Arm after delay to avoid instant fetch
  useEffect(() => {
    if (!enabled || libraries.length === 0) return;
    const t = setTimeout(() => setArmed(true), 500);
    return () => clearTimeout(t);
  }, [enabled, libraries]);

  // Prepare slices
const slices = useMemo(() => {
  return libraries
    .map((lib) => {
      const id = shopId(lib) as ShopId;
      const slice = shopStore.shops[id];

      if (!slice || slice.kind !== "AUTOGEN") return null;

      // Narrow lifecycle here
      const lifecycle = slice.lifecycle as AutogenShopLifecycle;

      return { lib, id, slice, lifecycle };
    })
    .filter(Boolean) as {
      lib: AutogenLibraryId;
      id: ShopId;
      slice: typeof shopStore.shops[ShopId];
      lifecycle: AutogenShopLifecycle;
    }[];
}, [libraries, shopStore.shops]);


  // Trigger backend ABC fetch
  useEffect(() => {
    if (!armed) return;

    slices.forEach(({ id, slice, lifecycle }) => {
      const hydrated = slice?.hydrated ?? false;
      const shouldFetch =
        (!hydrated || lifecycle === "CREATED" || lifecycle === "IMPORTING") &&
        !fetchedRef.current.has(id);

      if (!shouldFetch) return;

      fetchedRef.current.add(id);

      shopStore
        .runABC({ executionMode: "BACKEND", simulationType: "classic", shopId: id })
        .catch((err) => {
          errorRef.current = slice?.abc?.error ?? err;
        });
    });
  }, [armed, slices, shopStore]);

  // Show toast
  useApiErrorToast(errorRef.current, "Autogen Shop");

  // Build availability
  const perLibrary = slices.map(({ lib, slice, lifecycle }) => {
    const abcLoading = slice?.abc?.loading ?? false;
    const abcError = slice?.abc?.error;
    return {
      lib,
      lifecycle,
      unavailable: armed && (lifecycle === "FAILED" || !!abcError),
      available: armed && lifecycle === "READY",
      loading: abcLoading,
    };
  });

  return {
    unavailable: perLibrary.some((r) => r.unavailable),
    checking: armed && perLibrary.some((r) => r.loading),
    perLibrary,
  };
}



