import { useProductStore } from '@/store/inventory/useProductStore';
import type { Product } from '@/types/products';
import { toast } from 'sonner';

/**
 * Hook to import products from an autogenerated shop into the user's own shop
 */
export const useImportShopProducts = () => {
  const addProduct = useProductStore((s) => s.addProduct);

  const importProducts = async (sourceProducts: Product[]) => {
    if (sourceProducts.length === 0) {
      toast.error('No products to import from this shop.');
      return;
    }

    sourceProducts.forEach((p) =>
      addProduct({
        ...p,
        id: `${p.id}-${Date.now()}`, // avoid duplicate IDs
      })
    );

    toast.success(`${sourceProducts.length} products imported into your shop.`);
  };

  return { importProducts };
};
