import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import AddProduct from './forms/AddProduct';
import type { Product } from '@/types/products';
import ProductTable from './ProductTable';
import type { ShopMeta } from '@/store/shop/useShopStore';
import { useInventoryStore } from '@/store/inventory/useInventoryStore';
import { useEffect } from 'react';

/**
 * ShopStore owns shop identity and lifecycle.
 * ProductStore & InventoryStore own simulation state.
 * UI components never initialize domain state.
 */

export type ProductLibrarySource = 'manual' | 'florist' | 'cafeteria';

export interface ProductLibraryViewProps {
  ShopMeta?: ShopMeta;

  autogeneratedSource?: ProductLibrarySource;
  readonly?: boolean;

  products: Product[];
  loading?: boolean;
  isAutogen?: boolean;
}

const ProductLibraryView = ({
  ShopMeta: shopMeta,
  autogeneratedSource,
  readonly = false,
  products,
  loading = false,
  isAutogen,
}: ProductLibraryViewProps) => {
  return (
    <div>
      <Card className="shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="j-heading j-h1 text-left text-2x">
              My products
            </CardTitle>

            {shopMeta?.name ? (
              <p className="j-heading j-subtitle text-base font-normal sm:text-left">
                Managing products for <br />
                <span className="font-semibold">{shopMeta.name}</span>
              </p>
            ) : (
              <p className="j-heading j-subtitle text-base font-normal sm:text-left">
                Manage your product catalog
              </p>
            )}

            {autogeneratedSource && (
              <p className="text-xs text-muted-foreground mt-1">
                Imported from {autogeneratedSource} · Read-only baseline
              </p>
            )}
          </div>

          {!readonly && <AddProduct />}
        </CardHeader>

        <CardContent>
          <ProductTable
            products={products}
            loading={loading}
            readonly={readonly}
            shopMeta={shopMeta}
            isAutogen={isAutogen}
            autogeneratedSource={autogeneratedSource}
          />
        </CardContent>
      </Card>
    </div>
  );
};

export default ProductLibraryView;
