import  { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import AddProduct from "./forms/AddProduct";
import { type ShopId } from "@/types/shop";
import type { Product } from "@/types/products";



export type ProductLibrarySource =
  | "manual"
  | "florist"
  | "cafeteria";

export interface ProductLibraryViewProps {
  shopId: ShopId;
  shopName?: string;

  autogeneratedSource?: ProductLibrarySource;
  readonly?: boolean;

  products: Product[];
  loading?: boolean;
}

const ProductLibraryView = ({
  shopId,
  shopName,
  autogeneratedSource,
  readonly = false,
  products,
  loading = false,
}: ProductLibraryViewProps) => {

  // useInitProductData(); // loads JSON inventory if empty

  
  return (
    <div>
      <Card className="shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="j-heading j-h1  sm: text-left text-2x">My products</CardTitle>
            <p className="j-heading j-subtitle text-base font-normal sm:text-left">{shopName
                ? `Managing products for ${shopName}`
                : "Manage your product catalog"}</p>
            

            {autogeneratedSource && (
              <p className="text-xs text-muted-foreground mt-1">
                Imported from {autogeneratedSource} · Read-only baseline
              </p>
            )}
          </div>
          <AddProduct />
          
        </CardHeader>

        <CardContent>
          {/* <ProductTable data={products} loading={loading} /> */}
        </CardContent>
      </Card>
    </div>
  )
}

export default ProductLibraryView