import  { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import AddProduct from "./forms/AddProduct";
import type { Product } from "@/types/products";
import ProductTable from "./ProductTable";
import type { ShopMeta } from "@/store/shop/useShopStore";



export type ProductLibrarySource =
  | "manual"
  | "florist"
  | "cafeteria";

export interface ProductLibraryViewProps {

  ShopMeta: ShopMeta | undefined;

  autogeneratedSource?: ProductLibrarySource;
  readonly?: boolean;

  products: Product[];
  loading?: boolean;
}

const ProductLibraryView = ({
  ShopMeta: shopMeta,
  autogeneratedSource,
  readonly = false,
  products,
  loading = false,
}: ProductLibraryViewProps) => {

  // useInitProductData(); // loads JSON inventory if empty

  
  return (
    <div>
      <Card className="shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="j-heading j-h1  sm: text-left text-2x">My products</CardTitle>
            <p className="j-heading j-subtitle text-base font-normal sm:text-left">{shopMeta?.name
                ? `Managing products for ${shopMeta.name}`
                : "Manage your product catalog"}</p>
            

            {autogeneratedSource && (
              <p className="text-xs text-muted-foreground mt-1">
                Imported from {autogeneratedSource} · Read-only baseline
              </p>
            )}
          </div>
          {!readonly && <AddProduct />}
          
        </CardHeader>

        <CardContent>
          {/* <ProductTable data={products} loading={loading} /> */}
          <ProductTable
            products={products}
            loading={loading}
            readonly={readonly}
             shopMeta={shopMeta}
          />
           
        </CardContent>
      </Card>
    </div>
  )
}

export default ProductLibraryView