import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useShopInventoryProducts } from "@/hooks/shop/useShopInventoryProducts";
import { useProductStore } from "@/store/inventory/useProductStore";
import type { AbcRequestDto, SimulationType, AbcSelectableItem } from "@/types/abc-backend";
import Info from "@/views/helpers/Info";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState, useMemo, useEffect } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { abcSchema, type AbcFormValues } from "./props/Abc.schema";
import { toast } from "sonner";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { buildAbcRequest } from "@/utils/abc/buildABCRequest";
import { Trash2 } from "lucide-react";

const MODE_INFO = {
  title: "Simulation Mode",
  theory: "Classic vs Multi",
  description:
    "Classic: ABC based on value only. Multi: ABC based on value and demand frequency for a more comprehensive classification.",
};

const SALES_VALUE_INFO = {
  title: "Sales Value",
  theory: "Annual Consumption Value",
  description: `
Total monetary value generated by the product over a period (typically 1 year).
It is usually calculated as:

Sales Value = Unit Price × Quantity Sold

ABC classification in Classic mode is based primarily on this value.
`,
};

const DEMAND_FREQ_INFO = {
  title: "Demand Frequency",
  theory: "Order / Demand Occurrence Rate",
  description: `
How often the product is demanded within a given period 
(e.g., number of orders per month or per year).

In Multi mode, this metric is combined with Sales Value 
to better distinguish fast-moving and slow-moving items.
`,
};
interface AbcFormProps {
  onSubmit: (data: AbcRequestDto) => void;
  disabled?: boolean;
}

const AbcForm = ({ onSubmit, disabled = false }: AbcFormProps) => {
  const { products, inventory, loading } = useShopInventoryProducts();
  const isAuthenticated = useProductStore((s) => s.isAuthenticated);
  const [search, setSearch] = useState("");
  // const [selectedProduct, setSelectedProduct] = useState<AbcSelectableItem | null>(null);

  // ───────── React Hook Form ─────────
  const form = useForm<AbcFormValues>({
    resolver: zodResolver(abcSchema),
    defaultValues: {
      mode: "classic",
      saveToHistory: false,
      items: [],
    },
  });

  const { register, handleSubmit, watch, setValue, control, formState } = form;
  const { errors } = formState;

  const { fields, append, remove } = useFieldArray({
    control,
    name: "items",
  });

  // ───────── Inventory mapping ─────────
  const productOptions = useMemo(() => {
    if (!products || !inventory) return [];
    return inventory
      .map(inv => {
        const prod = products.find(p => p.id === inv.productId);
        if (!prod) return null;
        return {
          product: prod,
          quantity: inv.quantity,
          price: prod.unitPrice,
          cost: prod.unitCost,
          sku: prod.sku,
          category: prod.category,
          salesValue: 0,
          demandFrequency: 0,
        };
      })
      .filter(Boolean) as AbcSelectableItem[];
  }, [products, inventory]);

  const filteredProducts = useMemo(() => {
    return productOptions.filter(p =>
      `${p.product.sku ?? ""} ${p.product.name}`.toLowerCase().includes(search.toLowerCase())
    );
  }, [productOptions, search]);

  // ───────── Guest protection ─────────
  useEffect(() => {
    if (!isAuthenticated && watch("saveToHistory")) {
      setValue("saveToHistory", false);
    }
  }, [isAuthenticated, watch, setValue]);

  // ───────── Sync selected products with form array ─────────
  const toggleItemSelection = (item: AbcSelectableItem) => {
    const index = fields.findIndex((f) => f.product.id === item.product.id);
    if (index >= 0) remove(index);
    else append({ product: item.product, salesValue: 0, demandFrequency: 0 });
  };

  // ───────── Submit ─────────
  const submit = (values: AbcFormValues) => {
    if (!values.items.length) {
      toast.error("Please select at least one product.");
      return;
    }
   //Ability to add + than 1 prdct
    // const payload: AbcRequestDto = {
    //   items: values.items,
    //   mode: values.mode,
    //   saveToHistory: isAuthenticated ? values.saveToHistory : false,
    //   username: isAuthenticated ? undefined : "guest",
    // };
    const payload = buildAbcRequest(values, isAuthenticated);
    console.log("ABC payload ", payload)
    onSubmit(payload);
  };

  return (
      <Card>
      <CardHeader>
        <CardTitle>ABC Simulation</CardTitle>
        <CardDescription>
          Classify inventory items into A/B/C categories using{" "}
          <span className="font-medium">{watch("mode")}</span> mode.
        </CardDescription>
      </CardHeader>

      <CardContent>
        <form className="flex flex-col md:flex-row gap-6" onSubmit={handleSubmit(submit)}>
          
          {/* LEFT PANEL: Product Selection */}
          <div className="md:w-1/3 flex flex-col gap-4">
            <Label htmlFor="productSearch">Select Products</Label>
            <Input
              id="productSearch"
              placeholder={loading ? "Loading products..." : "Search by SKU or name"}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              disabled={loading}
            />

            <div className="border rounded-md overflow-hidden">
              <div className="max-h-[260px] overflow-y-auto">
                <Table className="text-sm">
                  <TableHeader>
                    <TableRow className="sticky top-0 bg-muted/50 z-10 text-muted-foreground">
                      <TableHead className="w-10 px-2 py-2"></TableHead>
                      <TableHead className="px-2 py-2 text-left">SKU</TableHead>
                      <TableHead className="px-2 py-2 text-left">Product</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredProducts.map((prod) => {
                      const checked = !!fields.find((f) => f.product.id === prod.product.id);
                      return (
                        <TableRow
                          key={prod.product.id}
                          onClick={() => toggleItemSelection(prod)}
                          className={`cursor-pointer transition-colors hover:bg-muted/50 ${checked ? "bg-muted" : ""}`}
                        >
                          <TableCell className="px-2 py-2">
                            <input type="checkbox" checked={checked} readOnly />
                          </TableCell>
                          <TableCell className="px-2 py-2 font-mono text-xs">{prod.product.sku || "—"}</TableCell>
                          <TableCell className="px-2 py-2">{prod.product.name}</TableCell>
                        </TableRow>
                      );
                    })}
                    {filteredProducts.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={3} className="px-4 py-6 text-center text-sm text-muted-foreground">
                          No products match your search
                        </TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>

          {/* RIGHT PANEL: Simulation Options + Selected Products */}
          <div className="md:w-2/3 grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Simulation Mode */}
            <div className="space-y-2">
              <div className="flex items-center gap-1">
                <Label>Simulation Mode</Label>
                <Info content={MODE_INFO} />
              </div>
              <Select
                value={watch("mode")}
                onValueChange={(value) =>
                  setValue("mode", value as SimulationType, { shouldValidate: true })
                }
                disabled={disabled || !fields.length}
              >
                <SelectTrigger className="toolbar-element btn-flat-btn toolbar-element-md active w-fit sm:w-auto">
                  <SelectValue placeholder="Select mode" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="classic">Classic</SelectItem>
                  <SelectItem value="multi">Multi</SelectItem>
                </SelectContent>
              </Select>
              {errors.mode && <p className="text-xs text-destructive">{errors.mode.message}</p>}
            </div>

            {/* Save to History */}
            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                {...register("saveToHistory")}
                disabled={!isAuthenticated || disabled || !fields.length}
                className="h-4 w-4 rounded border-muted"
              />
              <Label className="text-sm">Save to history</Label>
            </div>

            {/* Selected Products work*/}
            <div className="md:col-span-2 border rounded-md overflow-hidden">
              <div className="max-h-[400px] overflow-y-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Product</TableHead>

                      <TableHead className="w-24">Unit Price</TableHead>

                      <TableHead className="w-32">
                        <div className="flex items-center gap-1">
                          Quantity Sold
                          <Info content={SALES_VALUE_INFO} />
                        </div>
                      </TableHead>

                      <TableHead className="w-40 text-right">Sales Value</TableHead>

                      <TableHead className="w-40">
                        <div className="flex items-center gap-1">
                          Demand Freq
                          <Info content={DEMAND_FREQ_INFO} />
                        </div>
                      </TableHead>

                      <TableHead className="w-12"></TableHead>
                    </TableRow>
                  </TableHeader>

                  <TableBody>
                    {fields.map((field, idx) => {
                      const prod = productOptions.find(
                        (p) => p.product.id === field.product.id
                      )!;

                      // Watch quantity sold
                      const quantitySold = watch(`items.${idx}.salesValue`) || 0;
                      const calculatedSalesValue = quantitySold * prod.product.unitPrice;

                      return (
                        <TableRow key={field.id}>
                          {/* Product Info */}
                          <TableCell>
                            <div className="flex flex-col">
                              <span className="font-medium">{prod.product.name}</span>
                              <span className="text-xs text-muted-foreground">
                                {prod.product.sku ?? "—"} • {prod.product.category ?? "—"}
                              </span>
                            </div>
                          </TableCell>

                          {/* Unit Price (disabled) */}
                          <TableCell>
                            <Input
                              type="number"
                              value={prod.product.unitPrice}
                              disabled
                            className="h-8 w-20 bg-muted/20"
                            />
                          </TableCell>

                          {/* Quantity Sold */}
                          <TableCell>
                            <Input
                              type="number"
                              step={1}
                              min={0}
                              className="h-8"
                              {...register(`items.${idx}.salesValue` as const, {
                                valueAsNumber: true,
                              })}
                            />
                            {errors.items?.[idx]?.salesValue && (
                              <p className="text-xs text-destructive">
                                {errors.items[idx].salesValue?.message}
                              </p>
                            )}
                          </TableCell>

                          {/* Calculated Sales Value */}
                          <TableCell className="text-right font-medium">
                            {calculatedSalesValue.toFixed(2)}
                          </TableCell>

                          {/* Demand Frequency */}
                          <TableCell>
                            <Input
                              type="number"
                              step={1}
                              min={0}
                              className="h-8"
                              {...register(`items.${idx}.demandFrequency` as const, {
                                valueAsNumber: true,
                              })}
                            />
                            {errors.items?.[idx]?.demandFrequency && (
                              <p className="text-xs text-destructive">
                                {errors.items[idx].demandFrequency?.message}
                              </p>
                            )}
                          </TableCell>

                          {/* Remove Button */}
                          <TableCell>
                            <Button
                              type="button"
                              onClick={() => remove(idx)}
                               variant="destructive"
                               className="jbtn-danger h-8 w-8 p-0"
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </div>
            </div>

            {/* Submit Button */}
            <div className="md:col-span-2 flex justify-end pt-2">
              <Button
               type="submit"
               disabled={!fields.length || disabled}
               className="toolbar-element jbtn-flat-btn toolbar-element-md active"
               >
                Run ABC Simulation
              </Button>
            </div>
          </div>
        </form>
      </CardContent>
    </Card>



  );
};



export default AbcForm