import { useEffect, useMemo, useState } from 'react';
import { useShallow } from 'zustand/react/shallow';

import ModuleContainer from '../../ModuleContainer';
import ProductLibraryView from '@/views/inventory/ProductLibraryView';
import Info from '@/views/helpers/Info';
import ServiceUnavailable from '@/views/inventory/forms/ServiceUnavailable';
import ShopCreationWizardDialog from '@/views/inventory/forms/ShopCreationWizardDialog';

import { Button } from '@/components/ui/Button';

import { shopId } from '@/types/shop';
import { useShopProducts } from '@/hooks/shop/useShopProducts';
import { useShopStore, type ShopMeta } from '@/store/shop/useShopStore';
import { useProductStore } from '@/store/inventory/useProductStore';

import { useSelectedShop } from '@/hooks/shop/useSelectedShop';
import { useInventoryStore } from '@/store/inventory/useInventoryStore';
import { HousePlusIcon } from 'lucide-react';
import { isUserShopMeta, shopSliceToMeta } from '@/store/shop/adapter';
import { useInitSimulationStores } from '@/hooks/shop/useInitSimulationStores';


/**
 * Product Library module.
 * Manages product catalogs across user-created and autogenerated shops,
 * supports shop selection, creation wizard, and renders inventory views.
 * Handles autogen shop lifecycle, loading states, and read-only views for autogenerated data.
 */


/* ───────────────── AUTOGEN DEFINITIONS ───────────────── */

const AUTOGEN_SHOPS = [
  { id: shopId('FLORIST'), label: 'Florist shop', source: 'florist' as const },
  { id: shopId('CAFETERIA'), label: 'Cafeteria', source: 'cafeteria' as const },
] as const;

const PRODUCT_LIBRARY_INFO = {
  title: 'Product Library',
  theory: 'Shop-based inventory view',
  description:
    'You are managing the product catalog for the selected shop. Switch shops using the selector above to explore different inventories or create your own shop.',
};

/* ───────────────── COMPONENT ───────────────── */

const ProductLibraryModule = () => {
  const [wizardOpen, setWizardOpen] = useState(false); //Reset the wizard
  const [ackAutogenFailure, setAckAutogenFailure] = useState(false);

  // const [selection, setSelection] = useState<LibrarySelection>(null);
  const { shops, ensureAndSelectAutogenShop, ensureAutogenShop } = useShopStore(
    useShallow((s) => ({
      shops: s.shops,
      ensureAndSelectAutogenShop: s.ensureAndSelectAutogenShop,
      ensureAutogenShop: s.ensureAutogenShop,
    }))
  );

  const userProducts = useProductStore((s) => s.products);

  const {
    selectedId,
    shop: selectedShop,
    selectedSlice,
    selectShop,
  } = useSelectedShop();

  /* ───────────── Initialize + ensure AUTOGEN shops ───────────── */
  useEffect(() => {
    AUTOGEN_SHOPS.forEach((s) => ensureAutogenShop(s.id, s.label));
  }, [ensureAutogenShop]);

  useEffect(() => {
    setAckAutogenFailure(false);
  }, [selectedId]);

  /* ───────────── Derived selection ───────────── */

  const selection = useMemo(() => {
    if (!selectedId || !selectedSlice) return null;
    return { kind: selectedSlice.kind, shopId: selectedId };
  }, [selectedId, selectedSlice]);

  /* ───────────── AUTOGEN data ───────────── */

  const autogenShopId = selection?.kind === 'AUTOGEN' ? selection.shopId : null;

  const autogen = useShopProducts(autogenShopId, {
    enabled: !!autogenShopId,
    forceBackend: true,
  });

  /* ───────────── Store initialization  ───────────── */
  useInitSimulationStores(
    selectedShop,
    selection?.kind === 'AUTOGEN' ? autogen.products : userProducts
  );

  /* ───────────── View state ───────────── */

  const productsToShow =
    selection?.kind === 'AUTOGEN' ? autogen.products : userProducts;

  const loading = selection?.kind === 'AUTOGEN' ? autogen.loading : false;

  const readonly = selection?.kind === 'AUTOGEN';

  const autogeneratedSource =
    selection?.kind === 'AUTOGEN'
      ? AUTOGEN_SHOPS.find((s) => s.id === selection.shopId)?.source
      : undefined;

  // const showServiceUnavailable =
  //   selection?.kind === "AUTOGEN" && autogen.lifecycle === "FAILED";
  const showServiceUnavailable =
    selection?.kind === 'AUTOGEN' &&
    autogen.lifecycle === 'FAILED' &&
    !ackAutogenFailure;

  /* ───────────── User shop list ───────────── */
  const userShopMetas = useMemo(() => {
    return Object.entries(shops)
      .filter(([_, s]) => s.kind === 'USER' && s.lifecycle !== 'DELETED')
      .map(([id, s]) => shopSliceToMeta(shopId(id), s))
      .filter(isUserShopMeta)
      .sort((a, b) => b.createdAt - a.createdAt); // newest first
  }, [shops]);

  // const userShopLabels = userShopMetas.map((s) => s.name);

  /* ───────────── Selection helpers ───────────── */

  const selectUserShopByLabel = (label: string) => {
    const entry = Object.entries(shops).find(
      ([, s]) => s.kind === 'USER' && s.label === label
    );
    if (!entry) return;

    const [id, slice] = entry;
    const meta = shopSliceToMeta(shopId(id), slice);

    selectShop(meta);
  };

  const selectAutogenByLabel = (label: string) => {
    const def = AUTOGEN_SHOPS.find((s) => s.label === label);
    if (!def) return;

    useShopStore.getState().ensureAndSelectAutogenShop(def.id, def.label);

    const slice = useShopStore.getState().shops[def.id];
    if (!slice) return;

    selectShop(shopSliceToMeta(def.id, slice));
  };

  /* ───────────── Wizard callback ───────────── */

  const handleShopCreated = (shop: ShopMeta) => {
    selectShop(shop);
    useProductStore.getState().initForShop(shop);
    useInventoryStore.getState().initInventoryForShop(shop.id);
  };
  //
  const userCases = useMemo(
    () => [
      ...AUTOGEN_SHOPS.map((s) => s.label),
      ...userShopMetas.map((s) => s.name),
    ],
    [userShopMetas]
  );

  const selectedUserCase = selectedShop?.name ?? null;

  /* ───────────────── RENDER ───────────────── */

  return (
    <ModuleContainer
      title="Product Library"
      subtitle="Manage your products efficiently"
      breadcrumbTrail={[
        { label: 'Dashboard', path: '/dashboard' },
        { label: 'Inventory', path: '/dashboard/inventory' },
        { label: 'Product Library' },
      ]}
      userCases={userCases}
      userCasesPlaceholder="Import data shop"
      selectedUserCase={selectedUserCase}
      onUserCaseChange={(label) => {
        if (AUTOGEN_SHOPS.some((s) => s.label === label)) {
          selectAutogenByLabel(label);
        } else {
          selectUserShopByLabel(label);
        }
      }}
      renderUserCaseItem={(label) => {
        if (!AUTOGEN_SHOPS.some((s) => s.label === label)) {
          return (
            <div className="flex items-center justify-between w-full">
              <span>{label}</span>
              <HousePlusIcon
                size={16}
                className="text-blue-500 ml-2 cursor-pointer"
              />
            </div>
          );
        }
        return <span>{label}</span>;
      }}
      actions={
        <>
          <Info content={PRODUCT_LIBRARY_INFO} />
          <Button
            className="toolbar-element jbtn-flat-btn toolbar-element-md active"
            onClick={() => setWizardOpen(true)}
          >
            Create shop
          </Button>
          <Button className="toolbar-element jbtn-flat-btn toolbar-element-md">
            Stock
          </Button>
        </>
      }
    >
      <ShopCreationWizardDialog
        open={wizardOpen}
        onOpenChange={setWizardOpen}
        onShopCreated={handleShopCreated}
      />

      {showServiceUnavailable && (
        <ServiceUnavailable
          onCreateShop={() => {
            setAckAutogenFailure(true);
            setWizardOpen(true);
          }}
        />
      )}

      <ProductLibraryView
        ShopMeta={selectedShop ?? undefined}
        products={productsToShow}
        loading={loading}
        readonly={readonly}
        autogeneratedSource={autogeneratedSource}
        isAutogen={selection?.kind === 'AUTOGEN'}
      />
    </ModuleContainer>
  );
};

export default ProductLibraryModule;
