import { useState } from "react";
import { useShallow } from "zustand/react/shallow";

import ModuleContainer from "../../ModuleContainer";
import ProductLibraryView from "@/views/inventory/ProductLibraryView";
import Info from "@/views/ABCViews/info/Info";
import ServiceUnavailable from "@/views/inventory/forms/ServiceUnavailable";
import ShopCreationWizardDialog from "@/views/inventory/forms/ShopCreationWizardDialog";

import { Button } from "@/components/ui/Button";

import { shopId, type ShopId } from "@/types/shop";
import { useShopProducts } from "@/hooks/shop/useShopProducts";
import { useShopStore, type AutogenShopMeta } from "@/store/shop/useShopStore";
import { useProductStore } from "@/store/inventory/useProductStore";

import { useSelectedShop } from "@/hooks/shop/useSelectedShop";
import { useInventoryStore } from "@/store/inventory/useInventoryStore";

/* ───────────────── AUTOGEN DEFINITIONS ───────────────── */

const AUTOGEN_SHOPS = [
  { id: shopId("FLORIST"), label: "Florist shop", source: "florist" as const },
  { id: shopId("CAFETERIA"), label: "Cafeteria", source: "cafeteria" as const },
] as const;

const PRODUCT_LIBRARY_INFO = {
  title: "Product Library",
  theory: "Shop-based inventory view",
  description:
    "You are managing the product catalog for the selected shop. Switch shops using the selector above to explore different inventories or create your own shop.",
};

/* ───────────────── TYPES ───────────────── */

type LibrarySelection =
  | { kind: "AUTOGEN"; shopId: ShopId }
  | { kind: "USER" }
  | null;

/* ───────────────── COMPONENT ───────────────── */

const ProductLibraryModule = () => {
  const [wizardOpen, setWizardOpen] = useState(false);
  const [selection, setSelection] = useState<LibrarySelection>(null);


  const { shop, setShop, deleteUserShop } = useShopStore(
    useShallow((s) => ({ shop: s.shop, setShop: s.setShop, deleteUserShop: s.deleteUserShop }))
  );


  const userProducts = useProductStore((s) => s.products);

   const { selectedId: selectedShopId, shop: selectedShop, selectShop } = useSelectedShop();

  /* ───────────── Selected AUTOGEN shop ───────────── */

  const selectedAutogenId =
    selection?.kind === "AUTOGEN" ? selection.shopId : null;

  const autogen = useShopProducts(selectedAutogenId, {
    enabled: !!selectedAutogenId,
    forceBackend: true,
  });

  /* ───────────── Import wizard options ───────────── */

  // const importShopOptions: ShopOption[] = AUTOGEN_SHOPS.map((s) => ({
  //   id: s.id,
  //   label: s.label,
  //   products: selectedAutogenId === s.id ? autogen.products : [],
  // }));

  /* ───────────── View state ───────────── */

  const productsToShow =
    selection?.kind === "AUTOGEN" ? autogen.products : userProducts;

  const loading = selection?.kind === "AUTOGEN" && autogen.loading;
  const readonly = selection?.kind === "AUTOGEN";

  const autogeneratedSource =
    selection?.kind === "AUTOGEN"
      ? AUTOGEN_SHOPS.find((s) => s.id === selection.shopId)?.source
      : undefined;

  const showServiceUnavailable =
    selection?.kind === "AUTOGEN" && autogen.lifecycle === "FAILED";

  /* ───────────── Handlers ───────────── */

  const handleAutogenSelect = (id: ShopId) => {
    const def = AUTOGEN_SHOPS.find((s) => s.id === id);
    if (!def) return;

    setSelection({ kind: "AUTOGEN", shopId: id });

    const meta: AutogenShopMeta = {
      id: def.id,
      name: def.label,
      kind: "AUTOGEN",
      lifecycle: "CREATED",
    };

    setShop(meta);
    selectShop(id)
  };

    const handleUserSelect = (label: string) => {
    const shops = useShopStore.getState().shops;

       // find entry where kind === "USER" and label matches
          const entry = Object.entries(shops).find(
            ([id, slice]) => slice.kind === "USER" && slice.label === label
          );

          if (entry) {
            const [id, slice] = entry;

            // ensure label is defined (TypeScript-safe)
            if (!slice.label) return;

            setShop({
              id: shopId(slice.label),              // from record key
              name: slice.label, 
              kind: "USER",
              lifecycle: slice.lifecycle,
              createdAt: Date.now(),
              lastUpdated: Date.now(),
              lastSavedAt: Date.now(),
            });

            setSelection({ kind: "USER" });
            selectShop(shopId(slice.label));

            // Initialize product + inventory store for this user shop
          useProductStore.getState().initForShop({ id: id, name: slice.label });
          useInventoryStore.getState().initInventoryForShop(shopId(slice.label));
          }
    
  };

    const handleDeleteUserShop = (label: string) => {
      const shops = useShopStore.getState().shops;
      // find entry where kind === "USER" and label matches
      const entry = Object.entries(shops).find(
        ([id, slice]) => slice.kind === "USER" && slice.label === label
      );

      if (entry) {
        const [id, slice] = entry;

        // ensure label is defined (TypeScript-safe)
        if (!slice.label) return;
      // Delete shop + clear products/inventory
      deleteUserShop(shopId(slice.label));
      }
    };


  // select for user shop
  const userShopLabels = useShopStore(
    useShallow((s) =>
      Object.values(s.shops)
        .filter((shop) => shop.kind === "USER")
        .map((shop) => shop.label)
        .filter((label): label is string => typeof label === "string")
    )
  );


  /* ───────────────── RENDER ───────────────── */

  return (
    <ModuleContainer
      title="Product Library"
      subtitle="Manage your products efficiently"
      breadcrumbTrail={[
        { label: "Dashboard", path: "/dashboard" },
        { label: "Inventory", path: "/dashboard/inventory" },
        { label: "Product Library" },
      ]}
      userCases={[
         ...AUTOGEN_SHOPS.map((s) => s.label),
         ...userShopLabels,
      ]}
      userCasesPlaceholder="Import data shop"
      onUserCaseChange={(label) => {
          // check autogen shops first
          // const autogen = AUTOGEN_SHOPS.find((s) => s.label === label);
          // if (autogen) {
          //   handleAutogenSelect(autogen.id);
          //   return;
          // }

          // // user shops from store
          // const shops = useShopStore.getState().shops;

          // // find entry where kind === "USER" and label matches
          // const entry = Object.entries(shops).find(
          //   ([id, slice]) => slice.kind === "USER" && slice.label === label
          // );

          // if (entry) {
          //   const [id, slice] = entry;

          //   // ensure label is defined (TypeScript-safe)
          //   if (!slice.label) return;

          //   setShop({
          //     id: shopId(slice.label),              // from record key
          //     name: slice.label, 
          //     kind: "USER",
          //     lifecycle: slice.lifecycle,
          //     createdAt: Date.now(),
          //     lastUpdated: Date.now(),
          //     lastSavedAt: Date.now(),
          //   });

          //   setSelection({ kind: "USER" });
          // }
          if (AUTOGEN_SHOPS.some((s) => s.label === label)) {
          handleAutogenSelect(
            AUTOGEN_SHOPS.find((s) => s.label === label)!.id
          );
        } else {
          handleUserSelect(label);
        }

      }}
      actions={
        <>
          <Info content={PRODUCT_LIBRARY_INFO} />
          <Button
            className="toolbar-element jbtn-flat-btn toolbar-element-md active"
            onClick={() => setWizardOpen(true)}
          >
            Create shop
          </Button>
          <Button className="toolbar-element jbtn-flat-btn toolbar-element-md">
            Helpers
          </Button>
        </>
      }
    >
      <ShopCreationWizardDialog
        open={wizardOpen}
        onOpenChange={setWizardOpen}
      />

      {showServiceUnavailable && (
        <ServiceUnavailable onCreateShop={() => setWizardOpen(true)} />
      )}

      <ProductLibraryView
        ShopMeta={shop ?? undefined}
        products={productsToShow}
        loading={loading}
        readonly={readonly}
        autogeneratedSource={autogeneratedSource}
      />
    </ModuleContainer>
  );
};

export default ProductLibraryModule;