import { useState } from "react";
import { useShallow } from "zustand/react/shallow";
import ProductLibraryView from "@/views/inventory/ProductLibraryView";
import ModuleContainer from "../../ModuleContainer";
import { shopId, type ShopId } from "@/types/shop";
import { useShopProducts } from "@/hooks/shop/useShopProducts";
import { useShopStore, type AutogenShopMeta } from "@/store/shop/useShopStore";
import { useProductStore } from "@/store/inventory/useProductStore";
import Info from "@/views/ABCViews/info/Info";
import { Button } from "@/components/ui/Button";
import ServiceUnavailable from "@/views/inventory/forms/ServiceUnavailable";
import ShopCreationWizardDialog from "@/views/inventory/forms/ShopCreationWizardDialog";
import type { ShopOption } from "@/views/inventory/forms/steps/StepImportProducts";

const AUTOGEN_SHOPS = [
  { id: shopId("FLORIST"), label: "Florist shop", source: "florist" as const },
  { id: shopId("CAFETERIA"), label: "Cafeteria", source: "cafeteria" as const },
];

const PRODUCT_LIBRARY_INFO = {
  title: "Product Library",
  theory: "Shop-based inventory view",
  description:
    "You are managing the product catalog for the selected shop. Switch shops using the selector above to explore different inventories or create your own shop.",
};

type LibrarySelection =
  | { type: "autogen"; shopId: ShopId }
  | { type: "user" }
  | null;

const ProductLibraryModule = () => {
  const [wizardOpen, setWizardOpen] = useState(false);
  const [selection, setSelection] = useState<LibrarySelection>(null);

  // Zustand store for user shop
  const { shop, setShop } = useShopStore(
    useShallow((s) => ({ shop: s.shop, setShop: s.setShop }))
  );

  const userProducts = useProductStore((s) => s.products);

  // Determine selected autogen shop ID
  const autogenShopId = selection?.type === "autogen" ? selection.shopId : null;

  // Fetch autogen shop products
  const autogenShop = useShopProducts(autogenShopId, {
    enabled: !!autogenShopId,
    forceBackend: true,
  });

  // Prepare wizard / dropdown options
  const importShopOptions: ShopOption[] = AUTOGEN_SHOPS.map((s) => ({
    id: s.id,
    label: s.label,
    products: autogenShopId === s.id ? autogenShop.products : [],
  }));

  // Decide products to display
  const productsToShow = selection?.type === "autogen" ? autogenShop.products : userProducts;
  const loading = selection?.type === "autogen" ? autogenShop.loading : false;
  const readonly = selection?.type === "autogen";
  const autogeneratedSource =
    selection?.type === "autogen"
      ? AUTOGEN_SHOPS.find((s) => s.id === selection.shopId)?.source
      : undefined;

  const showServiceUnavailable =
    selection?.type === "autogen" && autogenShop.lifecycle === "FAILED";

  // --- Handlers ---
  const handleAutogenSelect = (selectedId: ShopId) => {
    // AUTOGEN_SHOPS has type { id, label, source }
    const shopData = AUTOGEN_SHOPS.find((s) => s.id === selectedId);
    if (!shopData) return;

    setSelection({ type: "autogen", shopId: selectedId });

    // Map AUTOGEN_SHOPS item to AutogenShopMeta
    const meta: AutogenShopMeta = {
      id: shopData.id,
      name: shopData.label, // map label -> name
      kind: "AUTOGEN",
      lifecycle: "CREATED",
    };

    setShop(meta);
  };

  const handleUserSelect = () => {
    setSelection({ type: "user" });
  };

  return (
    <ModuleContainer
      title="Product Library"
      subtitle="Manage your products efficiently"
      breadcrumbTrail={[
        { label: "Dashboard", path: "/dashboard" },
        { label: "Inventory", path: "/dashboard/inventory" },
        { label: "Product Library" },
      ]}
      userCases={[...AUTOGEN_SHOPS.map((s) => s.label), ...(shop ? [shop.name] : [])]}
      userCasesPlaceholder="Import data shop"
      onUserCaseChange={(label) => {
        const auto = AUTOGEN_SHOPS.find((s) => s.label === label);
        if (auto) return handleAutogenSelect(auto.id);
        if (shop?.name === label) return handleUserSelect();
      }}
      actions={
        <>
          <Info content={PRODUCT_LIBRARY_INFO} />
          <Button
            className="toolbar-element jbtn-flat-btn toolbar-element-md active"
            onClick={() => setWizardOpen(true)}
          >
            Create shop
          </Button>
          <Button className="toolbar-element jbtn-flat-btn toolbar-element-md">Helpers</Button>
        </>
      }
    >
      <ShopCreationWizardDialog
        open={wizardOpen}
        onOpenChange={setWizardOpen}
        importOptions={importShopOptions}
      />

      {showServiceUnavailable && (
        <ServiceUnavailable onCreateShop={() => setWizardOpen(true)} />
      )}

      <ProductLibraryView
        ShopMeta={shop ?? undefined}
        products={productsToShow}
        loading={loading}
        readonly={readonly}
        autogeneratedSource={autogeneratedSource}
      />
    </ModuleContainer>
  );
};

export default ProductLibraryModule;
