import type { ShopId, ShopSlice } from "@/types/shop";
import type { ShopMeta, UserShopMeta } from "./useShopStore";

export function shopSliceToMeta(
  id: ShopId,
  slice: ShopSlice
): ShopMeta {
  if (slice.kind === "AUTOGEN") {
    return {
      id,
      name: slice.label ?? "Autogenerated shop",
      kind: "AUTOGEN",
      lifecycle: slice.lifecycle,
    };
  }

  return {
    id,
    name: slice.label ?? "Unnamed shop",
    kind: "USER",
    lifecycle: slice.lifecycle,
    createdAt: Date.now(),
    lastUpdated: Date.now(),
    lastSavedAt: Date.now(),
  };
}


export function isUserShopMeta(shop: ShopMeta): shop is UserShopMeta {
  return shop.kind === "USER";
}
