import type { ShopId, ShopSlice } from "@/types/shop";
import type { ShopMeta, UserShopMeta } from "./useShopStore";
import type { StateCreator } from "zustand";


export function shopSliceToMeta(
  id: ShopId,
  slice: ShopSlice
): ShopMeta {
  if (slice.kind === "AUTOGEN") {
    return {
      id,
      name: slice.label ?? "Autogenerated shop",
      kind: "AUTOGEN",
      lifecycle: slice.lifecycle,

      //timestamps
      createdAt: slice.createdAt ?? Date.now(),
      lastUpdated: slice.lastUpdated ?? Date.now(),
      lastSavedAt: slice.lastSavedAt ?? Date.now(),

    };
  }

  return {
    id,
    name: slice.label ?? "Unnamed shop",
    kind: "USER",
    lifecycle: slice.lifecycle,
    createdAt: slice.createdAt!,
    lastUpdated: slice.lastUpdated!,
    lastSavedAt: slice.lastSavedAt!,
  };
}

export function isUserShopMeta(
  meta: ShopMeta
): meta is UserShopMeta {
  return meta.kind === "USER";
}


export type ShopSelectionSlice = {
  selectedShopId: ShopId | null;
  selectShop: (id: ShopId | null) => void;
};

export const createShopSelectionSlice: StateCreator<
  ShopSelectionSlice,
  [],
  [],
  ShopSelectionSlice
> = (set) => ({
  selectedShopId: null,
  selectShop: (id) => set({ selectedShopId: id }),
});
