import { Button } from "@/components/ui/Button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/label";
import { useInventoryStore, type InventoryItem } from "@/store/inventory/useInventoryStore";
import type { Product } from "@/types/products";
import { useEffect, useState } from "react";
import type { ProductLibrarySource } from "../ProductLibraryView";

interface AddToInventoryDialogProps {
    open: boolean; 
    onOpenChange: (open: boolean) => void;
    product: Product;
    inventoryItem: InventoryItem | undefined;
    shopName?: string;
    autogeneratedSource?: ProductLibrarySource;


}
const AddToInventoryDialog = ({
     open,
     onOpenChange,
      product,
      inventoryItem,
      shopName,
      autogeneratedSource
      }: AddToInventoryDialogProps) => {

       const addToInventory = useInventoryStore((s) => s.addToInventory);
       const isEdit = !!inventoryItem

       useEffect(() => {
          if (!open) setQuantity(0)
        }, [open])


        const [quantity, setQuantity] = useState<number>(0);

        const handleSubmit = () => {
            addToInventory(product.id!.toString(), quantity);
            setQuantity(0);
            onOpenChange(false);
        }
        
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="j-dialog max-w-md">
        <DialogHeader>
          <DialogTitle className="j-dialog-title text-center">
            {isEdit ? "Update Inventory Quantity" : "Add to Inventory"}
          </DialogTitle>

            <DialogDescription className="j-dialog-description text-center">
              {autogeneratedSource && (
              <div className="text-xs text-muted-foreground">
                Source catalog: <b>{autogeneratedSource}</b>
              </div>
            )}
            {shopName && (
              <>
                Managing inventory for <b>{shopName}</b>
                <br />
              </>
            )}

            {isEdit ? (
              <>
                <b>{product.name}</b> is already stocked.<br />
                Current quantity: <b>{inventoryItem?.quantity}</b>
              </>
            ) : (
              <>
                Choose how many units of <b>{product.name}</b> you want to stock.
              </>
            )}
          </DialogDescription>

        </DialogHeader>

        <div className="space-y-4 py-2">
          {/* Product Info (read-only context) */}
          <div className="rounded-md bg-muted p-3 text-sm">
            <div className="font-medium">{product.name}</div>
            <div className="text-muted-foreground">
              Cost: ${product.unitCost.toFixed(2)} · Price: $
              {product.unitPrice.toFixed(2)}
            </div>
          </div>

          {/* Quantity */}
          <div className="j-dialog-field">
            <Label className="j-dialog-label">
              {isEdit ? "Add units" : "Quantity (Units)"}
            </Label>
            <Input
              type="number"
              min={0}
              placeholder="Enter quantity"
              value={quantity}
              onChange={(e) => setQuantity(Number(e.target.value))}
            />
          </div>

          {/* Action */}
          <div className="flex justify-center pt-2">
            <Button
              className="jbtn-flat-btn jbtn-passive"
              onClick={handleSubmit}
              disabled={quantity <= 0}
            >
              {isEdit ? "Add Quantity" : "Add to Inventory"}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

export default AddToInventoryDialog