import { ABC_SCENARIOS } from "@/lib/abc/buildABCTableData";
import api from "@/services/api/api";
import type { ABCData } from "@/types/abc";
import type { SimulationType, AbcResponseDto } from "@/types/abc-backend";
import { shopId, type ShopId } from "@/types/shop";
import type { SimulatorABCOutput } from "@/types/simulator";
import { mapAbcResponseToTable } from "./mapper/abcBackendMapper";
import { ABCAnalysisFrontend } from "@/services/domain/segmentation/ABCAnalysisFrontend";
import { useShopStore } from "@/store/shop/useShopStore";
import { isAxiosError } from "axios";
import { getOrCreateSimId } from "@/utils/simulation";

//Flat ABC
export function runFrontendABC(
  items: ABCData[],
  scenario: keyof typeof ABC_SCENARIOS
): SimulatorABCOutput {

  
  // 1 Run frontend ABC analysis
  const { table, summary } = ABCAnalysisFrontend(items, ABC_SCENARIOS[scenario]);

  // 2 Wrap into AbcResponseDto to satisfy SimulatorABCResult
  const result: AbcResponseDto = {
    items: table.map((row, index) => ({
      product: row.product,
      salesValue: row.totalValue,
      rank: index + 1,
      cumulativePct: row.cumulative,
      abcCategoryType: row.category,
      demandFrequency:  1,
    
    })),
    summary: {
      totalValue: summary.totalValue,
      a: summary.A,
      b: summary.B,
      c: summary.C,
    },
  };

  // 3 Optionally, if you want a separate table for the frontend UI
  const tableForFrontend = mapAbcResponseToTable(result);

  return { result, table: tableForFrontend };

}

/**
 *
 * @param shopId shop identifier (e.g. "FLORIST", "CAFETERIA", "USER_123")
 * @param simulationType "classic" | "multi"
 */
export async function runShopABC(
  shopId: string,
  simulationType: SimulationType
): Promise<SimulatorABCOutput> {
   try {
    const shopPath = resolveShopPath(shopId);
    const simId = getOrCreateSimId(shopId);

    // const { data } = await api.get<AbcResponseDto>(
    //   `/simulations/${shopPath}/abc?mode=${simulationType.toUpperCase()}`
    // );
        const { data } = await api.get<AbcResponseDto>(
      `/simulations/${shopPath}/abc`,
      {
        params: {
          mode: simulationType.toUpperCase(),
          simId
        }
      }
    );

    
    const table = mapAbcResponseToTable(data);

    return {
      result: data,
      table,
    };
  } catch (err: unknown) {
    // Axios-style error narrowing
    if (isAxiosError(err)) {
      // Backend down / refused
      if (!err.response) {
        throw new Error("Cannot connect to backend");
      }

      // Backend responded with error
      throw new Error(
        err.response.data?.message ??
          `Generated sim shop failed (${err.response.status})`
      );
    }

    // Fallback
    throw new Error("Unexpected error - Sim generator shop service is currently unavailable");
  }
}


//Resolver for mapping path

function resolveShopPath(shopId: string): string {
  switch (shopId) {
    case "FLORIST":
      return "florist";
    case "CAFETERIA":
      return "cafeteria";
    default:
      // user-defined or future autogenerated shops
      return shopId.toLowerCase();
  }
}

export const SHOPS = {
  FLORIST: shopId("FLORIST"),
  CAFETERIA: shopId("CAFETERIA"),
} as const;


export const useShopProductsById = (id: ShopId) =>
  useShopStore((s) => s.shops[id]?.products ?? []);
